name: Test and Build Python Package

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # avoid bugs in new versions
        cache: 'pip'
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: |
        pip3 install -U pip
        pip3 install -e .[dev_all]

    - name: Test - Unit Test
      run: |
        pytest .

    - name: Test - Translate a PDF file with plain text only
      run:
        pdf2zh ./test/file/translate.cli.plain.text.pdf -o ./test/file

    - name: Test - Translate a PDF file figure
      run:
        pdf2zh ./test/file/translate.cli.text.with.figure.pdf -o ./test/file

    # - name: Test - Translate a PDF file with unknown font
    #   run:
    #     pdf2zh ./test/file/translate.cli.font.unknown.pdf

    - name: Test - Start GUI and exit
      run:
        timeout 10 pdf2zh -i  || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

    - name: Build as a package
      run: python -m build

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./test/file/
