name: Build Python Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build flake8 black

    - name: Test - Check code format
      run: |
        black --check --diff --color pdf2zh/*.py
        flake8 --ignore E203,E261,E501,W503,E741

    - name: Test - Install a local package
      run: 
        python -m pip install -e .

    - name: Test - Test the function of translating PDF to Chinese
      run: 
        pdf2zh translate.cli.plain.text

    # - name: Test - Test the function of starting GUI locally
    #   run: 
    #     pdf2zh -i

    - name: Build package
      run: python -m build
